### ISSUE TITLE
小栗帽剧本挑战完朝日杯后出现系统错误

### ISSUE THREAD

**Issue by DDKing-ZJU** [shiokaze/UmamusumeAutoTrainer#20]
参数：
支援卡：一颗安心糖 等级50 使用闹钟限制0
900-750-850-300-400
跑法：先-居中-居中
额外赛程 1701,2303,2401,5208,5407,5904
学习技能为空

Powershell 反馈如下
Traceback (most recent call last):
  File "F:\Program Files\Umamusume autotrainer\UmamusumeAutoTrainer-main\bot\engine\executor.py", line 116, in run_work_flow
    ctx.current_screen = ctx.ctrl.get_screen()
  File "F:\Program Files\Umamusume autotrainer\UmamusumeAutoTrainer-main\bot\conn\u2_ctrl.py", line 38, in get_screen
    cur_screen = self.u2client.screenshot(format='opencv')
  File "F:\Program Files\Umamusume autotrainer\UmamusumeAutoTrainer-main\venv\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "F:\Program Files\Umamusume autotrainer\UmamusumeAutoTrainer-main\venv\lib\site-packages\retry\api.py", line 73, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
  File "F:\Program Files\Umamusume autotrainer\UmamusumeAutoTrainer-main\venv\lib\site-packages\retry\api.py", line 33, in __retry_internal
    return f()
  File "F:\Program Files\Umamusume autotrainer\UmamusumeAutoTrainer-main\venv\lib\site-packages\uiautomator2\__init__.py", line 938, in screenshot
    r = self.http.get("/screenshot/0", timeout=10)
  File "F:\Program Files\Umamusume autotrainer\UmamusumeAutoTrainer-main\venv\lib\site-packages\requests\sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "F:\Program Files\Umamusume autotrainer\UmamusumeAutoTrainer-main\venv\lib\site-packages\uiautomator2\__init__.py", line 223, in request
    self.__client._prepare_atx_agent()
  File "F:\Program Files\Umamusume autotrainer\UmamusumeAutoTrainer-main\venv\lib\site-packages\uiautomator2\__init__.py", line 318, in _prepare_atx_agent
    version_url = self.path2url("/version")
  File "F:\Program Files\Umamusume autotrainer\UmamusumeAutoTrainer-main\venv\lib\site-packages\uiautomator2\__init__.py", line 301, in path2url
    return urlparse.urljoin(self._get_atx_agent_url(), path)
  File "F:\Program Files\Umamusume autotrainer\UmamusumeAutoTrainer-main\venv\lib\site-packages\uiautomator2\__init__.py", line 282, in _get_atx_agent_url
    lport = self._adb_device.forward_port(
  File "F:\Program Files\Umamusume autotrainer\UmamusumeAutoTrainer-main\venv\lib\site-packages\adbutils\_device.py", line 256, in forward_port
    self.forward("tcp:" + str(local_port), remote)
  File "F:\Program Files\Umamusume autotrainer\UmamusumeAutoTrainer-main\venv\lib\site-packages\adbutils\_device.py", line 246, in forward
    self.open_transport(":".join(args))
  File "F:\Program Files\Umamusume autotrainer\UmamusumeAutoTrainer-main\venv\lib\site-packages\adbutils\_device.py", line 97, in open_transport
    c.check_okay()
  File "F:\Program Files\Umamusume autotrainer\UmamusumeAutoTrainer-main\venv\lib\site-packages\adbutils\_adb.py", line 134, in check_okay
    raise AdbError(self.read_string_block())
adbutils.errors.AdbError: cannot bind listener: cannot bind to 127.0.0.1:3929: 通常每个套接字地址(协议/网络地址/端口)只 允许使用一次。 (10048)

**Comment by shiokaze** [comment]
看上去是偶现的网络问题，重启可以解决吗

**Comment by DDKing-ZJU** [comment]
重启可以解决，可能是个小问题
