### ISSUE TITLE
老哥这启动错误是哪里出问题了

### ISSUE THREAD

**Issue by NICEjj7** [shiokaze/UmamusumeAutoTrainer#35]
python : Traceback (most recent call last):
所在位置 D:\UmamusumeAutoTrainer-main\run.ps1:2 字符: 1
+ python main.py
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Traceback (most recent call last)::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
  File "D:\UmamusumeAutoTrainer-main\main.py", line 4, in <module>
    from bot.engine.scheduler import scheduler
  File "D:\UmamusumeAutoTrainer-main\bot\engine\scheduler.py", line 6, in <module>
    import croniter
ModuleNotFoundError: No module named 'croniter'

**Comment by shiokaze** [comment]
参考https://github.com/shiokaze/UmamusumeAutoTrainer/issues/31
