### ISSUE TITLE
选择比赛时程序报错list index out of range，卡在界面不动

### ISSUE THREAD

**Issue by inbrace419** [shiokaze/UmamusumeAutoTrainer#45]
![20230912081152](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/122359667/11f5c2fb-95c9-46a9-b8dc-2a13e0aa346f)
报错：
_FAILED
Traceback (most recent call last):
  File "D:\yousee\prettyderby\jiaoben\UmamusumeAutoTrainer-main\bot\engine\executor.py", line 126, in run_work_flow
    manifest.script(ctx)
  File "D:\yousee\prettyderby\jiaoben\UmamusumeAutoTrainer-main\module\umamusume\manifest.py", line 71, in exec_script
    script_dicts[ctx.task.task_type][ctx.current_ui](ctx)
  File "D:\yousee\prettyderby\jiaoben\UmamusumeAutoTrainer-main\module\umamusume\script\cultivate_task\cultivate.py", line 215, in script_cultivate_race_list
    selected = find_race(ctx, img, ctx.cultivate_detail.turn_info.turn_operation.race_id)
  File "D:\yousee\prettyderby\jiaoben\UmamusumeAutoTrainer-main\module\umamusume\script\cultivate_task\parse.py", line 361, in find_race
    target_race_template = RACE_LIST[race_id][2]
IndexError: list index out of range
2023-09-12 01:22:00,525     DEBUG --- [  run_work_flow] executor.py         : 任务结束

**Comment by shiokaze** [comment]
可以换场别的比赛看下会不会有一样的问题

**Comment by shiokaze** [comment]
已修复
