### ISSUE TITLE
运行异常，报错[Errno 503]

### ISSUE THREAD

**Issue by Tilie** [shiokaze/UmamusumeAutoTrainer#56]
> 2023-09-18 13:12:14,179  DEBUG    [       run_work_flow] executor.py         : 启动：com.bilibili.umamusu
2023-09-18 13:12:15,389  INFO     [            end_task] task.py             : 任务结束：TASK_STATUS_RUNNING-TASK_STATUS_FAILED
Traceback (most recent call last):
  File "C:\Users\35458\Desktop\de\UmamusumeAutoTrainer\bot\engine\executor.py", line 113, in run_work_flow
    ctx.ctrl.start_app(manifest.app_package_name)
  File "C:\Users\35458\Desktop\de\UmamusumeAutoTrainer\bot\conn\u2_ctrl.py", line 99, in start_app
    self.u2client.app_start(name)
  File "C:\Users\35458\Desktop\de\UmamusumeAutoTrainer\venv\lib\site-packages\uiautomator2\__init__.py", line 1434, in app_start
    info = self.app_info(package_name)
  File "C:\Users\35458\Desktop\de\UmamusumeAutoTrainer\venv\lib\site-packages\uiautomator2\__init__.py", line 1575, in app_info
    resp.raise_for_status()
  File "C:\Users\35458\Desktop\de\UmamusumeAutoTrainer\venv\lib\site-packages\uiautomator2\__init__.py", line 136, in raise_for_status
    raise requests.HTTPError(_self.status_code, _self.text)
requests.exceptions.HTTPError: [Errno 503]

没办法判断是哪部分出现了问题，能指点下吗

**Comment by shiokaze** [comment]
连接模拟器失败了，看下端口是否正确，以及模拟器上面的atx服务是否正常运行

**Comment by Tilie** [comment]
感谢解惑，我的问题解决了。
如有相同情况，请按照uiautomator2的教程，正确安装atx。
并确保没在终端中使用代理，代理可能导致连接失败。
