### ISSUE TITLE
图片获取不了

### ISSUE THREAD

**Issue by Chuannypiepie** [shiokaze/UmamusumeAutoTrainer#60]
![image](https://github.com/shiokaze/UmamusumeAutoTrainer/assets/92437852/aca5f176-3915-4037-bc08-faf8a8425833)
保存内容：Traceback (most recent call last):
  File "c:\Users\Chuanny\Desktop\UmamusumeAutoTrainer-main\bot\engine\executor.py", line 126, in run_work_flow
    manifest.script(ctx)
  File "c:\Users\Chuanny\Desktop\UmamusumeAutoTrainer-main\module\umamusume\manifest.py", line 71, in exec_script
    script_dicts[ctx.task.task_type][ctx.current_ui](ctx)
  File "c:\Users\Chuanny\Desktop\UmamusumeAutoTrainer-main\module\umamusume\script\cultivate_task\cultivate.py", line 103, in script_cultivate_training_select
    parse_training_result(ctx, img, train_type)
  File "c:\Users\Chuanny\Desktop\UmamusumeAutoTrainer-main\module\umamusume\script\cultivate_task\parse.py", line 278, in parse_training_result
    stamina_incr_text = ocr_line(sub_img_stamina_incr)
  File "c:\Users\Chuanny\Desktop\UmamusumeAutoTrainer-main\bot\recog\ocr.py", line 24, in ocr_line
    if len(text_info) > 0:
TypeError: 'NoneType' object is not iterable

在选择锻炼时图片获取不了

**Comment by shiokaze** [comment]
是偶然出现的还是一定出现的？

**Comment by ZJChe** [comment]
参考 #71
